name: build

on:
  push:
    branches:
      - 'main'
      - 'spring-3.1.x'
    paths:
      - 'src/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # todo version ranges may be better, but they don't work with dependencyManagement in maven 3
        version:
          - '2.7.15'
          - '3.0.10'
          - '3.1.3'
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw test -D"spring.boot.version=${{ matrix.version }}"
